#!/bin/bash

source src/functions;

DATABASE=$(cat src/database);

echo "Checking postgres status..." &&
checkPostgres &&

echo "Creating database..." &&
createDatabase $DATABASE &&

echo "Running scripts..." &&
runScripts $DATABASE;
